### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by yoyecros** [Disa-im/DisaBuilds#1]
Hello,

Is it normal that the archive (zip and tar.gz ) contains only the README.TXT and not the source code?

**Comment by walker93** [comment]
Disa framework source code is in the other repository. 
You can find it here: https://github.com/Disa-im/DisaOpenSource

This repository is used only for apk downloads

**Comment by yoyecros** [comment]
So what are these archives ? We can't see the source code of the app ?

**Comment by walker93** [comment]
No, the Android app source code is closed. Only the framework sources are released.

**Comment by yoyecros** [comment]
Ok, so I think you can rename or delete archives
